# Generated by Django 3.2.12 on 2023-12-17 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamiento', models.CharField(max_length=300)),
                ('capacidad', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('ubicacion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/oficinas')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='briall.oficina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
